#!/usr/bin/env bash
#
# Stage 2: assemble engine configuration from environment.
#
# Written to /etc/mysql/conf.d/10-mmdb-generated.cnf. Both engines include that
# directory, and files are read in alphabetical order, so a user override
# mounted as 90-local.cnf wins over these defaults -- which is what SPEC
# section 6 requires ("baked config is defaults only ... conf mounts still win").

MMDB_STAGE=mmdb-conf
export MMDB_STAGE
# shellcheck source=mmdb-lib.sh
source /usr/local/lib/mmdb/mmdb-lib.sh

stage "assembling configuration from environment"

mem_gb="${MMDB_MEM:-4}"
mem_mb=$(( mem_gb * 1024 ))

# InnoDB buffer pool is the MySQL-family equivalent of shared_buffers: about
# half of the memory budget, which is the conventional starting point.
buffer_pool=$(( mem_mb / 2 ))
(( buffer_pool < 128 )) && buffer_pool=128

slow_seconds="$(engine_env SLOW_SECONDS 1)"
nofile="$(engine_env NOFILE 10240)"

conf="$MMDB_CONF_DIR/10-mmdb-generated.cnf"

{
    printf '# Generated by my-multidb-server at container start. Do not edit.\n'
    printf '# Override by mounting a file into %s that sorts after this one,\n' "$MMDB_CONF_DIR"
    printf '# for example 90-local.cnf.\n\n'

    printf '[%s]\n' "$MMDB_CONF_SECTION"

    # SPEC section 6: utf8mb4 with an explicit collation. Neither engine
    # defaults to utf8mb4_unicode_ci -- MySQL 8.4 uses utf8mb4_0900_ai_ci and
    # MariaDB 11.4 uses utf8mb4_uca1400_ai_ci -- so leaving this implicit means
    # two engines that sort and compare text differently.
    printf 'character_set_server = utf8mb4\n'
    printf 'collation_server = utf8mb4_unicode_ci\n'

    # Explicit rather than inherited, so an upstream default change cannot
    # silently alter how the database validates data.
    printf "sql_mode = STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION\n"

    printf "default_time_zone = '%s'\n" "${MMDB_TZ:-UTC}"
    printf 'innodb_buffer_pool_size = %sM\n' "$buffer_pool"
    printf 'open_files_limit = %s\n' "$nofile"

    # Log to stdout so the container's logs are the engine's logs.
    printf 'log_error = stderr\n'

    if [[ "$slow_seconds" != "0" ]]; then
        printf 'slow_query_log = 1\n'
        printf 'long_query_time = %s\n' "$slow_seconds"
        printf 'slow_query_log_file = /dev/stderr\n'
    fi

    # MySQL 8.4 removed mysql_native_password from the default build. The
    # toggle exists for legacy clients that cannot speak caching_sha2_password.
    if [[ "$MMDB_ENGINE" == "mysql" ]] && is_true "$(engine_env NATIVE_PASSWORD_COMPAT false)"; then
        printf 'mysql_native_password = ON\n'
    fi

    # PITR. The MySQL family's equivalent of WAL archiving is the binary log.
    #
    # MySQL 8.0+ enables it by default; MariaDB does not, and neither
    # guarantees the settings that make a log REPLAYABLE. ROW format is the one
    # that matters: with STATEMENT, replaying a non-deterministic statement
    # (NOW(), UUID(), an unordered UPDATE ... LIMIT) produces different data
    # than it did the first time, so recovery silently diverges from the
    # database it is supposed to reproduce.
    if is_true "$(engine_env PITR false)"; then
        printf '\n# PITR: binary logging, replayable.\n'
        printf 'log_bin = %s\n' "${MMDB_BINLOG_BASENAME:-/var/lib/mmdb-binlog/binlog}"
        printf 'binlog_format = ROW\n'
        printf 'binlog_row_image = FULL\n'
        # Required for binary logging at all, and it must be stable: a server
        # that changes id between restarts breaks any replica or archiver
        # following it.
        printf 'server_id = %s\n' "$(engine_env SERVER_ID 1)"
        printf 'binlog_expire_logs_seconds = %s\n' "$(engine_env BINLOG_RETENTION_SECONDS 604800)"
        # Durability of the log itself. Without this a crash can lose the last
        # transactions from the binlog while they are committed in the data --
        # recovery would then silently stop short of them.
        printf 'sync_binlog = 1\n'
        printf 'innodb_flush_log_at_trx_commit = 1\n'
    fi

    # Test profile: the MySQL-family equivalents of PostgreSQL's fsync=off.
    # Set by compose.test.yml; data loss on stop is the point (SPEC section 7).
    if is_true "$(engine_env TEST_MODE false)"; then
        # Deliberately AFTER the PITR block, so sync_binlog=0 wins when both
        # are on: the test profile has already given up durability, and a
        # binlog it never replays is not worth an fsync per transaction.
        printf '\n# TEST PROFILE: durability deliberately disabled.\n'
        printf 'innodb_flush_log_at_trx_commit = 0\n'
        printf 'innodb_doublewrite = 0\n'
        printf 'sync_binlog = 0\n'
    fi
} > "$conf"

chmod 0644 "$conf"
stage "wrote $conf (innodb_buffer_pool_size=${buffer_pool}M, utf8mb4_unicode_ci)"
