#!/usr/bin/env bash
#
# Stage 2: assemble engine configuration from environment.
#
# Written to /etc/mysql/conf.d/10-dbtk-generated.cnf. Both engines include that
# directory, and files are read in alphabetical order, so a user override
# mounted as 90-local.cnf wins over these defaults -- which is what SPEC
# section 6 requires ("baked config is defaults only ... conf mounts still win").

DBTK_STAGE=dbtk-conf
export DBTK_STAGE
# shellcheck source=dbtk-lib.sh
source /usr/local/lib/dbtk/dbtk-lib.sh

stage "assembling configuration from environment"

mem_gb="${DBTK_MEM:-4}"
mem_mb=$(( mem_gb * 1024 ))

# InnoDB buffer pool is the MySQL-family equivalent of shared_buffers: about
# half of the memory budget, which is the conventional starting point.
buffer_pool=$(( mem_mb / 2 ))
(( buffer_pool < 128 )) && buffer_pool=128

slow_seconds="$(engine_env SLOW_SECONDS 1)"
nofile="$(engine_env NOFILE 10240)"

conf="$DBTK_CONF_DIR/10-dbtk-generated.cnf"

{
    printf '# Generated by db-toolkit at container start. Do not edit.\n'
    printf '# Override by mounting a file into %s that sorts after this one,\n' "$DBTK_CONF_DIR"
    printf '# for example 90-local.cnf.\n\n'

    printf '[%s]\n' "$DBTK_CONF_SECTION"

    # SPEC section 6: utf8mb4 with an explicit collation. Neither engine
    # defaults to utf8mb4_unicode_ci -- MySQL 8.4 uses utf8mb4_0900_ai_ci and
    # MariaDB 11.4 uses utf8mb4_uca1400_ai_ci -- so leaving this implicit means
    # two engines that sort and compare text differently.
    printf 'character_set_server = utf8mb4\n'
    printf 'collation_server = utf8mb4_unicode_ci\n'

    # Explicit rather than inherited, so an upstream default change cannot
    # silently alter how the database validates data.
    printf "sql_mode = STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION\n"

    printf "default_time_zone = '%s'\n" "${DBTK_TZ:-UTC}"
    printf 'innodb_buffer_pool_size = %sM\n' "$buffer_pool"
    printf 'open_files_limit = %s\n' "$nofile"

    # Log to stdout so the container's logs are the engine's logs.
    printf 'log_error = stderr\n'

    if [[ "$slow_seconds" != "0" ]]; then
        printf 'slow_query_log = 1\n'
        printf 'long_query_time = %s\n' "$slow_seconds"
        printf 'slow_query_log_file = /dev/stderr\n'
    fi

    # MySQL 8.4 removed mysql_native_password from the default build. The
    # toggle exists for legacy clients that cannot speak caching_sha2_password.
    if [[ "$DBTK_ENGINE" == "mysql" ]] && is_true "$(engine_env NATIVE_PASSWORD_COMPAT false)"; then
        printf 'mysql_native_password = ON\n'
    fi

    # Test profile: the MySQL-family equivalents of PostgreSQL's fsync=off.
    # Set by compose.test.yml; data loss on stop is the point (SPEC section 7).
    if is_true "$(engine_env TEST_MODE false)"; then
        printf '\n# TEST PROFILE: durability deliberately disabled.\n'
        printf 'innodb_flush_log_at_trx_commit = 0\n'
        printf 'innodb_doublewrite = 0\n'
        printf 'sync_binlog = 0\n'
    fi
} > "$conf"

chmod 0644 "$conf"
stage "wrote $conf (innodb_buffer_pool_size=${buffer_pool}M, utf8mb4_unicode_ci)"
