#!/usr/bin/env bash
#
# Stage 3: TLS certificates.
#
# Mounted CA-issued certificates take precedence. When none are mounted we do
# nothing and let the engine fall back to its own behaviour, which differs and
# is worth stating:
#
#   MySQL 8.4  generates a self-signed pair into the data directory at init and
#              reuses it thereafter.
#   MariaDB 11.4 generates an EPHEMERAL, in-memory certificate on every start
#              and writes nothing to disk. Verified empirically in DESIGN.md
#              D-13: have_ssl=YES while ssl_ca/ssl_cert/ssl_key stay empty.
#
# The practical consequence is that a client cannot use verify-full against
# MariaDB's automatic certificate, because it changes at every restart. That is
# exactly why `make certs` and a mounted CA are mandatory rather than optional.

MDB_STAGE=mdb-certs
export MDB_STAGE
# shellcheck source=mdb-lib.sh
source /usr/local/lib/mdb/mdb-lib.sh

stage "preparing TLS material"

src_dir=""
for candidate in "/certs/$MDB_ENGINE" /certs; do
    if [[ -r "$candidate/server.crt" && -r "$candidate/server.key" ]]; then
        src_dir="$candidate"
        break
    fi
done

if [[ -z "$src_dir" ]]; then
    stage "no certificates mounted; leaving the engine's own TLS behaviour in place"
    if is_true "${MDB_TLS_ENFORCE:-false}"; then
        die "MDB_TLS_ENFORCE=true but no certificates are mounted at /certs; run make certs"
    fi
    exit 0
fi

stage "using mounted certificates from $src_dir"

install -o mysql -g mysql -m 0600 "$src_dir/server.crt" "$MDB_CERT_DIR/server.crt"
install -o mysql -g mysql -m 0600 "$src_dir/server.key" "$MDB_CERT_DIR/server.key"
[[ -r /certs/ca.crt ]] && install -o mysql -g mysql -m 0644 /certs/ca.crt "$MDB_CERT_DIR/ca.crt"

conf="$MDB_CONF_DIR/15-mdb-tls.cnf"
{
    printf '# Generated by multidb-server.\n'
    printf '[%s]\n' "$MDB_CONF_SECTION"
    printf 'ssl_cert = %s/server.crt\n' "$MDB_CERT_DIR"
    printf 'ssl_key = %s/server.key\n' "$MDB_CERT_DIR"
    [[ -r "$MDB_CERT_DIR/ca.crt" ]] && printf 'ssl_ca = %s/ca.crt\n' "$MDB_CERT_DIR"

    # SPEC section 9.1: under enforcement the server refuses plaintext TCP.
    # Unix sockets count as a secure transport and keep working, which is what
    # makes this safe to turn on in prod without breaking local tooling.
    if is_true "${MDB_TLS_ENFORCE:-false}"; then
        printf 'require_secure_transport = ON\n'
    fi
} > "$conf"

chmod 0644 "$conf"
stage "wrote $conf (require_secure_transport=${MDB_TLS_ENFORCE:-false})"
