#!/usr/bin/env bash
#
# Stage 2: assemble postgresql configuration from environment.
#
# Baked defaults only. Everything here is overridable, and mounted override
# files sort AFTER the generated file inside conf.d so they win -- which is what
# SPEC section 13 requires ("image defaults + mounted conf.d overrides").
#
# Settings are written to a config file rather than passed as `-c` arguments
# because command-line arguments outrank config files in PostgreSQL, which
# would invert that precedence and make user overrides impossible.

DBTK_STAGE=dbtk-conf
export DBTK_STAGE
# The absolute path is correct inside the image; this tells shellcheck where
# to find the same file in the repository.
# shellcheck source=dbtk-lib.sh
source /usr/local/lib/dbtk/dbtk-lib.sh

stage "assembling configuration from environment"

mem_gb="${DBTK_MEM:-4}"
cpus="${DBTK_CPUS:-2}"

# PGTune-style sizing from the two knobs SPEC section 13 specifies. Integer
# arithmetic in MB throughout; bash has no floating point.
mem_mb=$(( mem_gb * 1024 ))
shared_buffers=$(( mem_mb / 4 ))
effective_cache=$(( mem_mb * 3 / 4 ))
maintenance_work_mem=$(( mem_mb / 20 ))
(( maintenance_work_mem > 2048 )) && maintenance_work_mem=2048
(( maintenance_work_mem < 64 )) && maintenance_work_mem=64
max_connections="${DBTK_PG_MAX_CONNECTIONS:-100}"
work_mem=$(( (mem_mb / 4) / max_connections ))
(( work_mem < 4 )) && work_mem=4

conf="$DBTK_CONF_DIR/10-dbtk-generated.conf"

{
    printf '# Generated by db-toolkit at container start. Do not edit.\n'
    printf '# Override by mounting a file into %s that sorts after this one,\n' "$DBTK_CONF_DIR"
    printf '# for example 90-local.conf.\n\n'

    printf "listen_addresses = '*'\n"
    printf 'max_connections = %s\n' "$max_connections"
    printf "shared_buffers = '%sMB'\n" "$shared_buffers"
    printf "effective_cache_size = '%sMB'\n" "$effective_cache"
    printf "maintenance_work_mem = '%sMB'\n" "$maintenance_work_mem"
    printf "work_mem = '%sMB'\n" "$work_mem"
    printf 'max_worker_processes = %s\n' "$(( cpus > 2 ? cpus : 2 ))"
    printf "timezone = '%s'\n" "${DBTK_TZ:-UTC}"
    printf "log_timezone = '%s'\n" "${DBTK_TZ:-UTC}"

    # SPEC section 12: slow query logging, dev on / prod off.
    printf 'log_min_duration_statement = %s\n' "${DBTK_PG_SLOW_MS:-500}"
    printf "log_destination = 'stderr'\n"
    printf 'logging_collector = off\n'

    # SPEC section 9: scram everywhere, no trust, not even on localhost.
    printf "password_encryption = 'scram-sha-256'\n"

    if [[ -n "${DBTK_PG_SHARED_PRELOAD:-}" ]]; then
        printf "shared_preload_libraries = '%s'\n" "$DBTK_PG_SHARED_PRELOAD"
    fi

    # pg_cron must be told which database hosts its tables, or it fails to load.
    case "${DBTK_PG_SHARED_PRELOAD:-}" in
        *pg_cron*) printf "cron.database_name = '%s'\n" "${POSTGRES_DB:-postgres}" ;;
    esac

    # Test profile: speed over durability, set by compose.test.yml. Data loss
    # on stop is the point (SPEC section 7), so these are safe here and
    # catastrophic anywhere else.
    #
    # fsync=off alone is not enough: synchronous_commit=off removes the WAL
    # flush wait and full_page_writes=off removes torn-page protection, both
    # of which only buy durability the test profile has already given up.
    if is_true "${DBTK_PG_TEST_MODE:-false}"; then
        printf '\n# TEST PROFILE: durability deliberately disabled.\n'
        printf 'fsync = off\n'
        printf 'synchronous_commit = off\n'
        printf 'full_page_writes = off\n'
    fi
} > "$conf"

stage "wrote $conf (shared_buffers=${shared_buffers}MB, work_mem=${work_mem}MB, max_connections=$max_connections)"

# PostgreSQL only reads a directory if postgresql.conf includes it. Two
# directories, in this order, because order decides precedence: the generated
# configuration first, then user overrides, so a mounted file always wins
# (SPEC section 13).
include_block="include_dir = '$DBTK_CONF_DIR'
include_dir = '$DBTK_OVERRIDE_CONF_DIR'"

marker="# db-toolkit include"

if pgdata_initialised; then
    if ! grep -qF "$marker" "$PGDATA_DIR/postgresql.conf" 2>/dev/null; then
        printf '\n%s\n%s\n' "$marker" "$include_block" >> "$PGDATA_DIR/postgresql.conf"
        stage "added include_dir directives to the existing postgresql.conf"
    fi
else
    # On a first run the data directory does not exist yet, so this is deferred
    # to an initdb.d hook that runs after initdb has created postgresql.conf.
    cat > "$DBTK_INITDB_DIR/00-dbtk-include.sh" <<EOF
#!/usr/bin/env bash
# Added by db-toolkit: make PostgreSQL read the generated configuration.
set -eu
if ! grep -qF "$marker" "\$PGDATA/postgresql.conf"; then
    printf '\n%s\n%s\n' "$marker" "$include_block" >> "\$PGDATA/postgresql.conf"
fi
EOF
    chmod +x "$DBTK_INITDB_DIR/00-dbtk-include.sh"
    stage "queued include_dir directives for first initdb"
fi

# The override directory must exist, or PostgreSQL refuses to start on a
# missing include_dir. It is normally supplied by a compose mount; creating it
# here keeps a bare `docker run` working too.
mkdir -p "$DBTK_OVERRIDE_CONF_DIR" 2>/dev/null || true
