#!/usr/bin/env bash
#
# Stage 2: assemble postgresql configuration from environment.
#
# Baked defaults only. Everything here is overridable, and mounted override
# files sort AFTER the generated file inside conf.d so they win -- which is what
# SPEC section 13 requires ("image defaults + mounted conf.d overrides").
#
# Settings are written to a config file rather than passed as `-c` arguments
# because command-line arguments outrank config files in PostgreSQL, which
# would invert that precedence and make user overrides impossible.

DBTK_STAGE=dbtk-conf
export DBTK_STAGE
# The absolute path is correct inside the image; this tells shellcheck where
# to find the same file in the repository.
# shellcheck source=dbtk-lib.sh
source /usr/local/lib/dbtk/dbtk-lib.sh

stage "assembling configuration from environment"

mem_gb="${DBTK_MEM:-4}"
cpus="${DBTK_CPUS:-2}"

# PGTune-style sizing from the two knobs SPEC section 13 specifies. Integer
# arithmetic in MB throughout; bash has no floating point.
mem_mb=$(( mem_gb * 1024 ))
shared_buffers=$(( mem_mb / 4 ))
effective_cache=$(( mem_mb * 3 / 4 ))
maintenance_work_mem=$(( mem_mb / 20 ))
(( maintenance_work_mem > 2048 )) && maintenance_work_mem=2048
(( maintenance_work_mem < 64 )) && maintenance_work_mem=64
max_connections="${DBTK_PG_MAX_CONNECTIONS:-100}"
work_mem=$(( (mem_mb / 4) / max_connections ))
(( work_mem < 4 )) && work_mem=4

conf="$DBTK_CONF_DIR/10-dbtk-generated.conf"

{
    printf '# Generated by db-toolkit at container start. Do not edit.\n'
    printf '# Override by mounting a file into %s that sorts after this one,\n' "$DBTK_CONF_DIR"
    printf '# for example 90-local.conf.\n\n'

    printf "listen_addresses = '*'\n"
    printf 'max_connections = %s\n' "$max_connections"
    printf "shared_buffers = '%sMB'\n" "$shared_buffers"
    printf "effective_cache_size = '%sMB'\n" "$effective_cache"
    printf "maintenance_work_mem = '%sMB'\n" "$maintenance_work_mem"
    printf "work_mem = '%sMB'\n" "$work_mem"
    printf 'max_worker_processes = %s\n' "$(( cpus > 2 ? cpus : 2 ))"
    printf "timezone = '%s'\n" "${DBTK_TZ:-UTC}"
    printf "log_timezone = '%s'\n" "${DBTK_TZ:-UTC}"

    # SPEC section 12: slow query logging, dev on / prod off.
    printf 'log_min_duration_statement = %s\n' "${DBTK_PG_SLOW_MS:-500}"
    printf "log_destination = 'stderr'\n"
    printf 'logging_collector = off\n'

    # SPEC section 9: scram everywhere, no trust, not even on localhost.
    printf "password_encryption = 'scram-sha-256'\n"

    if [[ -n "${DBTK_PG_SHARED_PRELOAD:-}" ]]; then
        printf "shared_preload_libraries = '%s'\n" "$DBTK_PG_SHARED_PRELOAD"
    fi

    # pg_cron must be told which database hosts its tables, or it fails to load.
    case "${DBTK_PG_SHARED_PRELOAD:-}" in
        *pg_cron*) printf "cron.database_name = '%s'\n" "${POSTGRES_DB:-postgres}" ;;
    esac

    # PITR. archive_mode is NOT reloadable -- it needs a server restart -- so
    # it has to be decided here, before the server starts, rather than
    # converged afterwards like the pooler's objects.
    #
    # Off by default. WAL archiving on a development machine fills a disk with
    # segments nobody will ever replay, and a toolkit that silently did that
    # would be diagnosed as a disk leak. The prod profile requires it.
    if is_true "${DBTK_PG_PITR:-false}"; then
        printf '\n# PITR: WAL archiving to the pgBackRest repository.\n'
        printf 'archive_mode = on\n'
        # %%p in a printf FORMAT emits a single %p, which is what
        # postgresql.conf needs. Emitting %%p instead makes PostgreSQL treat it
        # as an escaped literal and hand pgbackrest the two characters "%p"
        # rather than the WAL path -- every archive fails, pg_wal grows, and the
        # first backup hangs waiting for a segment that will never arrive.
        printf "archive_command = 'pgbackrest --stanza=%s archive-push %%p'\n" \
            "${DBTK_PGBACKREST_STANZA:-dbtk}"
        # replica is the minimum that allows archive recovery; the HA path
        # already sets it for streaming.
        printf 'wal_level = replica\n'
        # Without this an idle database can leave the last partial segment
        # unarchived indefinitely, so the recoverable point silently stops
        # advancing while everything looks healthy.
        printf 'archive_timeout = %s\n' "${DBTK_PG_ARCHIVE_TIMEOUT:-60}"
    fi

    # Test profile: speed over durability, set by compose.test.yml. Data loss
    # on stop is the point (SPEC section 7), so these are safe here and
    # catastrophic anywhere else.
    #
    # fsync=off alone is not enough: synchronous_commit=off removes the WAL
    # flush wait and full_page_writes=off removes torn-page protection, both
    # of which only buy durability the test profile has already given up.
    if is_true "${DBTK_PG_TEST_MODE:-false}"; then
        printf '\n# TEST PROFILE: durability deliberately disabled.\n'
        printf 'fsync = off\n'
        printf 'synchronous_commit = off\n'
        printf 'full_page_writes = off\n'
    fi
} > "$conf"

stage "wrote $conf (shared_buffers=${shared_buffers}MB, work_mem=${work_mem}MB, max_connections=$max_connections)"

# -----------------------------------------------------------------------------
# pgBackRest configuration
# -----------------------------------------------------------------------------
# Written whenever PITR is on, because archive-push runs as a child of the
# server and reads this file -- an archive_command pointing at a stanza with no
# configuration fails on every segment, and PostgreSQL retries forever while
# pg_wal grows.
if is_true "${DBTK_PG_PITR:-false}"; then
    stanza="${DBTK_PGBACKREST_STANZA:-dbtk}"
    pgbr_conf=/etc/pgbackrest/pgbackrest.conf
    mkdir -p /etc/pgbackrest

    {
        printf '[global]\n'
        printf 'repo1-retention-full=%s\n' "${DBTK_PGBACKREST_RETENTION_FULL:-2}"
        printf 'start-fast=y\n'
        printf 'compress-type=zst\n'
        printf 'log-level-console=info\n'
        printf 'log-level-file=off\n'

        case "${DBTK_PGBACKREST_REPO_TYPE:-posix}" in
            s3)
                # The same repository, off the machine. A backup on the host
                # that failed is not a backup, and this is the only setting
                # that changes where it lives.
                printf 'repo1-type=s3\n'
                printf 'repo1-path=%s\n' "${DBTK_PGBACKREST_S3_PATH:-/pgbackrest}"
                printf 'repo1-s3-bucket=%s\n' "${DBTK_PGBACKREST_S3_BUCKET:?S3 repo needs DBTK_PGBACKREST_S3_BUCKET}"
                printf 'repo1-s3-endpoint=%s\n' "${DBTK_PGBACKREST_S3_ENDPOINT:?S3 repo needs DBTK_PGBACKREST_S3_ENDPOINT}"
                printf 'repo1-s3-region=%s\n' "${DBTK_PGBACKREST_S3_REGION:-us-east-1}"
                [[ -n "${DBTK_PGBACKREST_S3_URI_STYLE:-}" ]] \
                    && printf 'repo1-s3-uri-style=%s\n' "$DBTK_PGBACKREST_S3_URI_STYLE"
                printf 'repo1-s3-key=%s\n' "$(tr -d '\n' < /run/secrets/pgbackrest_s3_key.txt)"
                printf 'repo1-s3-key-secret=%s\n' "$(tr -d '\n' < /run/secrets/pgbackrest_s3_secret.txt)"
                # Encrypted at rest, because object storage is somebody else's
                # disk. The passphrase is generated by `make init`.
                if [[ -r /run/secrets/pgbackrest_cipher_passphrase.txt ]]; then
                    printf 'repo1-cipher-type=aes-256-cbc\n'
                    printf 'repo1-cipher-pass=%s\n' \
                        "$(tr -d '\n' < /run/secrets/pgbackrest_cipher_passphrase.txt)"
                fi
                ;;
            *)
                printf 'repo1-type=posix\n'
                printf 'repo1-path=%s\n' "${DBTK_PGBACKREST_REPO_PATH:-/var/lib/pgbackrest}"
                ;;
        esac

        printf '\n[%s]\n' "$stanza"
        printf 'pg1-path=%s\n' "$PGDATA_DIR"
        printf 'pg1-socket-path=/var/run/postgresql\n'
    } > "$pgbr_conf"

    # It holds an S3 secret key and a cipher passphrase.
    chmod 0600 "$pgbr_conf"
    chown postgres:postgres "$pgbr_conf"

    mkdir -p "${DBTK_PGBACKREST_REPO_PATH:-/var/lib/pgbackrest}"
    chown -R postgres:postgres "${DBTK_PGBACKREST_REPO_PATH:-/var/lib/pgbackrest}"

    stage "PITR on: repo type ${DBTK_PGBACKREST_REPO_TYPE:-posix}, stanza $stanza"
fi

# PostgreSQL only reads a directory if postgresql.conf includes it. Two
# directories, in this order, because order decides precedence: the generated
# configuration first, then user overrides, so a mounted file always wins
# (SPEC section 13).
include_block="include_dir = '$DBTK_CONF_DIR'
include_dir = '$DBTK_OVERRIDE_CONF_DIR'"

marker="# db-toolkit include"

if pgdata_initialised; then
    if ! grep -qF "$marker" "$PGDATA_DIR/postgresql.conf" 2>/dev/null; then
        printf '\n%s\n%s\n' "$marker" "$include_block" >> "$PGDATA_DIR/postgresql.conf"
        stage "added include_dir directives to the existing postgresql.conf"
    fi
else
    # On a first run the data directory does not exist yet, so this is deferred
    # to an initdb.d hook that runs after initdb has created postgresql.conf.
    cat > "$DBTK_INITDB_DIR/00-dbtk-include.sh" <<EOF
#!/usr/bin/env bash
# Added by db-toolkit: make PostgreSQL read the generated configuration.
set -eu
if ! grep -qF "$marker" "\$PGDATA/postgresql.conf"; then
    printf '\n%s\n%s\n' "$marker" "$include_block" >> "\$PGDATA/postgresql.conf"
fi
EOF
    chmod +x "$DBTK_INITDB_DIR/00-dbtk-include.sh"
    stage "queued include_dir directives for first initdb"
fi

# The override directory must exist, or PostgreSQL refuses to start on a
# missing include_dir. It is normally supplied by a compose mount; creating it
# here keeps a bare `docker run` working too.
mkdir -p "$DBTK_OVERRIDE_CONF_DIR" 2>/dev/null || true
