#!/usr/bin/env bash
#
# Stage 3: TLS certificates.
#
# SPEC decision 5: PostgreSQL TLS is always on. Mounted CA-issued certificates
# take precedence; if none are mounted the image generates a self-signed pair so
# a bare `docker run` still gets an encrypted server rather than silently
# falling back to plaintext.
#
# Keys land 0600 owned by postgres. PostgreSQL refuses to start otherwise, which
# is why this stage depends on dbtk-perms having run first.

DBTK_STAGE=dbtk-certs
export DBTK_STAGE
# The absolute path is correct inside the image; this tells shellcheck where
# to find the same file in the repository.
# shellcheck source=dbtk-lib.sh
source /usr/local/lib/dbtk/dbtk-lib.sh

stage "preparing TLS material"

src_crt=""
src_key=""
src_ca=""

# Mounted toolkit certificates, as written by `make certs` on the host.
for candidate in /certs/pg /certs; do
    if [[ -r "$candidate/server.crt" && -r "$candidate/server.key" ]]; then
        src_crt="$candidate/server.crt"
        src_key="$candidate/server.key"
        [[ -r /certs/ca.crt ]] && src_ca=/certs/ca.crt
        break
    fi
done

if [[ -n "$src_crt" ]]; then
    stage "using mounted certificates from $(dirname "$src_crt")"
    install -o postgres -g postgres -m 0600 "$src_crt" "$DBTK_CERT_DIR/server.crt"
    install -o postgres -g postgres -m 0600 "$src_key" "$DBTK_CERT_DIR/server.key"
    if [[ -n "$src_ca" ]]; then
        install -o postgres -g postgres -m 0644 "$src_ca" "$DBTK_CERT_DIR/ca.crt"
    fi
elif [[ -s "$DBTK_CERT_DIR/server.crt" ]]; then
    stage "reusing previously generated self-signed certificate"
else
    stage "no certificates mounted; generating a self-signed pair"
    sans="DNS:localhost,DNS:pg,DNS:postgres,IP:127.0.0.1"
    if [[ -n "${DBTK_EXTRA_SANS:-}" ]]; then
        IFS=',' read -ra extra <<< "$DBTK_EXTRA_SANS"
        for s in "${extra[@]}"; do
            [[ -n "$s" ]] && sans="$sans,DNS:$s"
        done
    fi
    openssl req -x509 -newkey rsa:2048 -nodes \
        -days "${DBTK_CERT_DAYS:-825}" \
        -subj "/CN=$(hostname)" \
        -addext "subjectAltName=$sans" \
        -keyout "$DBTK_CERT_DIR/server.key" \
        -out "$DBTK_CERT_DIR/server.crt" >/dev/null 2>&1 \
        || die "failed to generate a self-signed certificate"
    chown postgres:postgres "$DBTK_CERT_DIR/server.key" "$DBTK_CERT_DIR/server.crt"
    chmod 0600 "$DBTK_CERT_DIR/server.key" "$DBTK_CERT_DIR/server.crt"
fi

# Emit the TLS configuration. This sorts before any mounted override, so a user
# can still turn TLS off deliberately.
tls_conf="$DBTK_CONF_DIR/15-dbtk-tls.conf"
{
    printf '# Generated by db-toolkit. TLS is on by default (SPEC decision 5).\n'
    printf 'ssl = on\n'
    printf "ssl_cert_file = '%s/server.crt'\n" "$DBTK_CERT_DIR"
    printf "ssl_key_file = '%s/server.key'\n" "$DBTK_CERT_DIR"
    if [[ -s "$DBTK_CERT_DIR/ca.crt" ]]; then
        printf "ssl_ca_file = '%s/ca.crt'\n" "$DBTK_CERT_DIR"
    fi
    printf "ssl_min_protocol_version = 'TLSv1.2'\n"
} > "$tls_conf"

stage "wrote $tls_conf"

# Under enforcement every TCP rule becomes hostssl, so plaintext TCP is refused
# by the server. Unix sockets are a secure transport and keep working, which
# SPEC section 9.1 requires explicitly.
if is_true "${DBTK_TLS_ENFORCE:-false}"; then
    stage "TLS enforcement on: pg_hba will be hostssl-only"
    cat > "$DBTK_INITDB_DIR/01-dbtk-hba.sh" <<'EOF'
#!/usr/bin/env bash
set -eu
sed -i 's/^host\([[:space:]]\)/hostssl\1/' "$PGDATA/pg_hba.conf"
EOF
    chmod +x "$DBTK_INITDB_DIR/01-dbtk-hba.sh"

    if pgdata_initialised; then
        sed -i 's/^host\([[:space:]]\)/hostssl\1/' "$PGDATA_DIR/pg_hba.conf"
        stage "rewrote existing pg_hba.conf to hostssl"
    fi

    if is_true "${DBTK_MTLS:-false}"; then
        stage "mutual TLS on: client certificates required"
        sed -i 's/^hostssl\(.*\)scram-sha-256$/hostssl\1scram-sha-256 clientcert=verify-full/' \
            "$PGDATA_DIR/pg_hba.conf" 2>/dev/null || true
    fi
fi
