#!/usr/bin/env bash
#
# Stage 3: TLS certificates.
#
# SPEC decision 5: PostgreSQL TLS is always on. Mounted CA-issued certificates
# take precedence; if none are mounted the image generates a self-signed pair so
# a bare `docker run` still gets an encrypted server rather than silently
# falling back to plaintext.
#
# Keys land 0600 owned by postgres. PostgreSQL refuses to start otherwise, which
# is why this stage depends on mmdb-perms having run first.

MMDB_STAGE=mmdb-certs
export MMDB_STAGE
# The absolute path is correct inside the image; this tells shellcheck where
# to find the same file in the repository.
# shellcheck source=mmdb-lib.sh
source /usr/local/lib/mmdb/mmdb-lib.sh

stage "preparing TLS material"

src_crt=""
src_key=""
src_ca=""

# Mounted toolkit certificates, as written by `make certs` on the host.
for candidate in /certs/pg /certs; do
    if [[ -r "$candidate/server.crt" && -r "$candidate/server.key" ]]; then
        src_crt="$candidate/server.crt"
        src_key="$candidate/server.key"
        [[ -r /certs/ca.crt ]] && src_ca=/certs/ca.crt
        break
    fi
done

if [[ -n "$src_crt" ]]; then
    stage "using mounted certificates from $(dirname "$src_crt")"
    install -o postgres -g postgres -m 0600 "$src_crt" "$MMDB_CERT_DIR/server.crt"
    install -o postgres -g postgres -m 0600 "$src_key" "$MMDB_CERT_DIR/server.key"
    if [[ -n "$src_ca" ]]; then
        install -o postgres -g postgres -m 0644 "$src_ca" "$MMDB_CERT_DIR/ca.crt"
    fi
elif [[ -s "$MMDB_CERT_DIR/server.crt" ]]; then
    stage "reusing previously generated self-signed certificate"
else
    stage "no certificates mounted; generating a self-signed pair"
    sans="DNS:localhost,DNS:pg,DNS:postgres,IP:127.0.0.1"
    if [[ -n "${MMDB_EXTRA_SANS:-}" ]]; then
        IFS=',' read -ra extra <<< "$MMDB_EXTRA_SANS"
        for s in "${extra[@]}"; do
            [[ -n "$s" ]] && sans="$sans,DNS:$s"
        done
    fi
    openssl req -x509 -newkey rsa:2048 -nodes \
        -days "${MMDB_CERT_DAYS:-825}" \
        -subj "/CN=$(hostname)" \
        -addext "subjectAltName=$sans" \
        -keyout "$MMDB_CERT_DIR/server.key" \
        -out "$MMDB_CERT_DIR/server.crt" >/dev/null 2>&1 \
        || die "failed to generate a self-signed certificate"
    chown postgres:postgres "$MMDB_CERT_DIR/server.key" "$MMDB_CERT_DIR/server.crt"
    chmod 0600 "$MMDB_CERT_DIR/server.key" "$MMDB_CERT_DIR/server.crt"
fi

# Emit the TLS configuration. This sorts before any mounted override, so a user
# can still turn TLS off deliberately.
tls_conf="$MMDB_CONF_DIR/15-mmdb-tls.conf"
{
    printf '# Generated by my-multidb-server. TLS is on by default (SPEC decision 5).\n'
    printf 'ssl = on\n'
    printf "ssl_cert_file = '%s/server.crt'\n" "$MMDB_CERT_DIR"
    printf "ssl_key_file = '%s/server.key'\n" "$MMDB_CERT_DIR"
    if [[ -s "$MMDB_CERT_DIR/ca.crt" ]]; then
        printf "ssl_ca_file = '%s/ca.crt'\n" "$MMDB_CERT_DIR"
    fi
    printf "ssl_min_protocol_version = 'TLSv1.2'\n"
} > "$tls_conf"

stage "wrote $tls_conf"

# -----------------------------------------------------------------------------
# Authentication hardening (SPEC section 9: no trust, anywhere, including
# localhost).
# -----------------------------------------------------------------------------
# initdb generates a pg_hba.conf that trusts the local socket AND loopback TCP.
# That means any process inside the container -- a compromised extension, a
# sidecar sharing the network namespace, an untrusted procedural language --
# connects as the superuser with no credential. It also makes password rotation
# impossible to verify, because a loopback connection succeeds whatever the
# password is.
#
# What replaces it:
#   local  -> peer with an ident map, so identity is the OS user rather than
#             nothing at all. SPEC section 10.1 reserves peer for exactly this,
#             "make-driven maintenance as the engine user".
#   host   -> scram-sha-256, loopback included. No exceptions for 127.0.0.1.

if pgdata_initialised; then
    harden_hba "$PGDATA_DIR/pg_hba.conf"
    write_ident_map "$PGDATA_DIR/pg_ident.conf"
    stage "hardened pg_hba: no trust rules remain"
else
    # On a first run PGDATA does not exist yet, so this is deferred to an
    # initdb.d hook. It sources the same functions rather than duplicating
    # them, so the rules cannot drift between the two paths.
    cat > "$MMDB_INITDB_DIR/01-mmdb-auth.sh" <<'EOF'
#!/usr/bin/env bash
# Added by my-multidb-server: replace the trust rules initdb generates
# (SPEC section 9 forbids trust anywhere, including localhost).
set -eu
MMDB_STAGE=mmdb-auth
export MMDB_STAGE
# shellcheck source=/dev/null
source /usr/local/lib/mmdb/mmdb-lib.sh
harden_hba "$PGDATA/pg_hba.conf"
write_ident_map "$PGDATA/pg_ident.conf"
EOF
    chmod +x "$MMDB_INITDB_DIR/01-mmdb-auth.sh"
    stage "queued pg_hba hardening for first initdb"
fi

# Under enforcement every TCP rule becomes hostssl, so plaintext TCP is refused
# by the server. Unix sockets are a secure transport and keep working, which
# SPEC section 9.1 requires explicitly.
if is_true "${MMDB_TLS_ENFORCE:-false}"; then
    stage "TLS enforcement on: pg_hba will be hostssl-only"
    cat > "$MMDB_INITDB_DIR/02-mmdb-tls-hba.sh" <<'EOF'
#!/usr/bin/env bash
set -eu
sed -i 's/^host\([[:space:]]\)/hostssl\1/' "$PGDATA/pg_hba.conf"
EOF
    chmod +x "$MMDB_INITDB_DIR/02-mmdb-tls-hba.sh"

    if pgdata_initialised; then
        sed -i 's/^host\([[:space:]]\)/hostssl\1/' "$PGDATA_DIR/pg_hba.conf"
        stage "rewrote existing pg_hba.conf to hostssl"
    fi

    if is_true "${MMDB_MTLS:-false}"; then
        stage "mutual TLS on: client certificates required"
        sed -i 's/^hostssl\(.*\)scram-sha-256$/hostssl\1scram-sha-256 clientcert=verify-full/' \
            "$PGDATA_DIR/pg_hba.conf" 2>/dev/null || true
    fi
fi
