#!/usr/bin/env bash
# shellcheck shell=bash
#
# Shared helpers for the my-multidb-server-pg s6 init stages.

set -euo pipefail

# Generated state lives under /run, which is tmpfs. That is what lets the
# container run with a read-only root filesystem (SPEC section 9, DESIGN.md
# D-18) without a bespoke tmpfs mount for every directory we write to.
MMDB_CONF_DIR=/run/mmdb/conf.d
MMDB_CERT_DIR=/run/mmdb/certs

# User-supplied overrides are mounted here and stay read-only. PostgreSQL reads
# this directory AFTER the generated one, so a mounted file wins -- which is
# what SPEC section 13 requires.
MMDB_OVERRIDE_CONF_DIR=/etc/postgresql/conf.d

MMDB_INITDB_DIR=/docker-entrypoint-initdb.d
PGDATA_DIR="${PGDATA:-/var/lib/postgresql/data}"

export MMDB_CONF_DIR MMDB_CERT_DIR MMDB_OVERRIDE_CONF_DIR MMDB_INITDB_DIR PGDATA_DIR

# Every stage announces itself. The harness asserts the observed order in
# scripts/verify/10-s6-init-and-shutdown.sh, so these strings are load-bearing.
stage() { printf '[%s] %s\n' "$MMDB_STAGE" "$*"; }

die() { printf '[%s] FATAL: %s\n' "${MMDB_STAGE:-mmdb}" "$*" >&2; exit 1; }

# Resolve a value that may be given directly or through the _FILE convention.
# SPEC decision 6: secrets travel as files, never as plain env.
resolve_secret() {
    local direct="${1:-}" file="${2:-}"
    if [[ -n "$file" ]]; then
        [[ -r "$file" ]] || die "secret file is not readable: $file"
        tr -d '\n' < "$file"
        return
    fi
    printf '%s' "$direct"
}

# Is the data directory already initialised?
pgdata_initialised() { [[ -s "$PGDATA_DIR/PG_VERSION" ]]; }

# true/false env helper.
is_true() {
    case "${1:-}" in
        true|TRUE|True|1|yes|YES|on|ON) return 0 ;;
        *) return 1 ;;
    esac
}

# -----------------------------------------------------------------------------
# Authentication hardening. Defined here, not in the stage script, because the
# first-run initdb.d hook needs the identical rules and a second copy would
# eventually disagree with the first.
# -----------------------------------------------------------------------------
# The file is generated whole rather than patched. Patching the initdb output
# means guessing at its exact spacing and missing whatever a future release
# adds; generating it means the rules are exactly what is written here.
#
# The split is the one SPEC section 10.1 specifies: peer for maintenance as the
# engine user, scram for app roles, on sockets as much as on TCP. An earlier
# attempt made ALL local auth peer, which locked application roles out of the
# socket entirely -- correct about trust, wrong about who peer is for.
harden_hba() {
    local hba="$1"
    [[ -f "$hba" ]] || return 0

    cat > "$hba" <<'EOF'
# Generated by my-multidb-server at container start. Do not edit; edit the image.
#
# SPEC section 9:    no trust or empty-password auth anywhere, localhost
#                    included.
# SPEC section 10.1: peer is reserved for make-driven maintenance as the
#                    engine user; app roles use scram, sockets included.

# Maintenance over the unix socket as the engine role. `docker exec` runs as
# root, which pg_ident maps to postgres, so peer still verifies a real OS
# identity rather than accepting anyone the way trust did.
local   all             postgres                                peer map=mmdb

# Every other role authenticates, on the socket too.
local   all             all                                     scram-sha-256

# Loopback TCP is not special. This is the rule initdb ships as `trust`, and
# the reason a rotated password appeared to still work.
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Replication.
local   replication     all                                     peer map=mmdb
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256

# Everything else, including other containers on the toolkit network.
host    all             all             all                     scram-sha-256
EOF
    chmod 0600 "$hba"
    chown postgres:postgres "$hba" 2>/dev/null || true
}

# The ident map lets root -- which is what `docker exec` runs as -- act as the
# postgres role over the socket. Peer still verifies a real OS identity, which
# trust did not do at all; this narrows it to a named user rather than anyone.
write_ident_map() {
    local ident="$1"
    [[ -f "$ident" ]] || return 0
    grep -q '^mmdb[[:space:]]' "$ident" 2>/dev/null && return 0
    {
        printf '\n# my-multidb-server: allow container maintenance as the engine role.\n'
        printf '# MAPNAME   SYSTEM-USERNAME   PG-USERNAME\n'
        printf 'mmdb        root              postgres\n'
        printf 'mmdb        postgres          postgres\n'
    } >> "$ident"
}
